/* ========== Dados estáticos / constantes do jogo ========== */

export const DEFAULT_CATEGORIES = [
  'Aquecimento',
  'Preliminares',
  'Masturbação',
  'Oral',
  'Submissão',
  'Pesado'
];

export const BUILTIN_CHALLENGES = [
  { "text": "Faça uma garganta profunda na(o) {player}", "category": "Pesado", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 1 },
  { "text": "Sente no rosto do(a) {player}", "category": "Pesado", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 1 },
  { "text": "Tire uma peça de roupa do(a) {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 1 },
  { "text": "Tire uma peça de roupa", "category": "Preliminares", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 1 },
  { "text": "Beijo sexy no(a) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 1 },
  { "text": "Beijar o pescoço do(a) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 1 },
  { "text": "Passe seus pés pelo corpo do(a) {player}", "category": "Aquecimento", "actorGender": "F", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Chupe o dedo da(o) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Massageie os seios da {player} por cima da roupa", "category": "Aquecimento", "actorGender": "any", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Chupe a orelha do(a) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Lamba a bunda da(o) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Acaricie o rosto do(a) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Passe a lingua no tronco da(o) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Acaricie o seu corpo com as mãos do(a) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Morder a orelha do(a) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Morder a bunda do(a) {player}", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Masturbe o(a) {player} por cima da roupa", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Masturbe o {player} com seus peitos", "category": "Masturbação", "actorGender": "F", "targetGender": "M", "allowSelf": false, "weight": 2 },
  { "text": "Masturbe o {player} com seus pés", "category": "Masturbação", "actorGender": "F", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Se masturbe com os pés da {player}", "category": "Masturbação", "actorGender": "any", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Acaricie o pênis do {player}", "category": "Masturbação", "actorGender": "any", "targetGender": "M", "allowSelf": false, "weight": 2 },
  { "text": "Penetre a {player} com os dedos", "category": "Masturbação", "actorGender": "any", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Masturbe o(a) {player} com suas mãos", "category": "Masturbação", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Faça sexo oral na(o) {player}", "category": "Oral", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Faça um 69 com {player}", "category": "Oral", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Passe a língua no clitóris da {player}", "category": "Oral", "actorGender": "any", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Faça sexo oral no(a) {player}", "category": "Oral", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Deixe a {player} molhada", "category": "Oral", "actorGender": "any", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Deixe o pênis do {player} bem molhado", "category": "Oral", "actorGender": "any", "targetGender": "M", "allowSelf": false, "weight": 2 },
  { "text": "Transe com a {player} no estilo papai-e-mamãe", "category": "Pesado", "actorGender": "M", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Transe com o(a) {player} no estilo frango assado", "category": "Pesado", "actorGender": "M", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Transe com o(a) {player} de quatro", "category": "Pesado", "actorGender": "M", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Passe seu pênis nos peitos da(o) {player}", "category": "Preliminares", "actorGender": "M", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Chupe os seios da {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Chupe os mamilos do {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "M", "allowSelf": false, "weight": 2 },
  { "text": "Massageie os seios da {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Faça o que quiser com o(a) {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Sopre o pênis do {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "M", "allowSelf": false, "weight": 2 },
  { "text": "Sopre a vagina da {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Acaricie o seu corpo com as mãos do(a) {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Massagem no(a) {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Beijar o corpo do(a) {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Dar uma palmada no(a) {player}", "category": "Preliminares", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Rebole para o(a) {player}", "category": "Preliminares", "actorGender": "F", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Amarre a(o) {player} e faça o que quiser", "category": "Submissão", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Chicoteie o(a) {player}", "category": "Submissão", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Enfie a mão na calcinha e acaricie-se por alguns instantes. Em seguida passe os dedos pelos lábios do(a) {player}", "category": "Aquecimento", "actorGender": "F", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Masturbe o(a) {player} enquanto ele(a) te masturba", "category": "Masturbação", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Faça tesourinha com (a) {player}", "category": "Masturbação", "actorGender": "F", "targetGender": "F", "allowSelf": false, "weight": 2 },
  { "text": "Sente no rosto do(a) {player} enquanto o(a) masturba", "category": "Oral", "actorGender": "F", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Fique em pé se masturbando enquanto {player} lambe seus testículos ajoelhada", "category": "Oral", "actorGender": "M", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Fique sentado enquanto {player} monta no seu colo para se esfregar em você", "category": "Preliminares", "actorGender": "M", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Fique em pé enquanto {player} te chupa", "category": "Oral", "actorGender": "M", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Fale no ouvido da(o) {player} como você chamaria ela(e) na cama", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Prenda a(o) {player} contra a parede ou chão e beije o pescoço", "category": "Aquecimento", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Sussurre no ouvido da(o) {player}, em detalhes, o que você imagina fazer com ele. Sem filtro.", "category": "Preliminares", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Fique deitado(a), enquanto {player} se masturba bem próximo do seu rosto. Você só pode olhar, sem encostar", "category": "Masturbação", "actorGender": "any", "targetGender": "any", "allowSelf": false, "weight": 2 },
  { "text": "Aperte o pescoço da {player} para beija-la", "category": "Aquecimento", "actorGender": "any", "targetGender": "M", "allowSelf": false, "weight": 2 },
];
